version: '3'

services:
  mock:
    container_name: vulnerability-engine-mock
    build: ./mock
    image: vulnerability-engine/mock:latest
    restart: unless-stopped
    ports:
      - 8080:8080

  server:
    container_name: vulnerability-engine-server
    build: ./server
    image: vulnerability-engine/server:latest
    restart: unless-stopped
    ports:
      - 8000:8000
